# Generated by Django 5.1.5 on 2025-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_chatmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmodel",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
